name: Deploy via FTP

on:
  push:
    branches:
      - main # Asegúrate de cambiar esto si deseas desplegar desde otra rama

jobs:
  ftp-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: git-ftp push
        uses: sebastianpopp/git-ftp-action@releases/v3
        with:
          url: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
