name: Deploy via FTP

on:
  push:
    branches:
      - main # Asegúrate de cambiar esto si deseas desplegar desde otra rama

jobs:
  ftp-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to FTP server
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ftp://${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: /var/www/alvarommedia/html/qr-code-component/ # Ajusta esto a la ruta en tu servidor donde quieras desplegar
