name: FTP Deploy
on: [push]
jobs:
  ftp-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: List files in the repo
        run: ls

      - name: FTP Deploy Action
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          ftp-server: ftp://${{ secrets.FTP_SERVER }}
          ftp-username: ${{ secrets.FTP_USERNAME }}
          ftp-password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./qr-code-component/
          git-ftp-args: --insecure
